////
This guide is maintained in the main Quarkus repository
and pull requests should be submitted there:
https://github.com/quarkusio/quarkus/tree/main/docs/src/main/asciidoc
////
= Creating Your First Braineous Data Ingestion Application
include::_attributes.adoc[]
:categories: getting-started
:summary: Discover how to create your first Braineous data ingestion application.
:numbered:
:sectnums:
:sectnumlevels: 4
:topics: getting-started

Learn how to create a Braineous Data Ingestion application.

This guide covers:

* Get the Source Data
* Register a data pipe and send source data to multiple target MongoDB databases
* Verify all target databases receive the data

== Prerequisites

:prerequisites-no-graalvm:
include::{includes}/prerequisites.adoc[]

[TIP]
.Verify Maven is using the Java you expect
====
If you have multiple JDK's installed, it is not certain Maven will pick up the expected java
and you could end up with unexpected results.
You can verify which JDK Maven uses by running `mvn --version`.
====


== Get the Source Data

We recommend that you follow the instructions to create the application step by step.

However, you can go right to the completed example.

Download an {quickstarts-archive-url}[archive] or clone the git repository:

Let's start with a simple Json array to be used as datasource to be
ingested by the Braineous Data Ingestion Engine

Source Data
[source,bash,subs=attributes+]
----
[
  {
    "id" : 1,
    "name": "Joe Black1",
    "age": 50,
    "addr": {
      "email": "test@email.com",
      "phone": "123456"
    }
  },
  {
    "id": "2",
    "name": "Joe Black2",
    "age": 50,
    "addr": {
      "email": "test@email.com",
      "phone": "123456"
    }
  }
]
----

Java Code
[source,bash,subs=attributes+]
----
String datasetLocation = "tutorial/usecase/scenario1/scenario1Array.json";

String json = Util.loadResource(datasetLocation);

JsonElement datasetElement = JsonUtil.validateJson(json);
----

== Register a data pipe and send source data to multiple target MongoDB databases

Register a data pipe with the Braineous Data Ingestion Engine using the
Java Braineous Data Ingestion Client SDK.

Pipe Configuration
[source,bash,subs=attributes+]
----
{
  "pipeId": "123",
  "configuration": [
    {
      "storeDriver" : "com.appgallabs.dataplatform.receiver.core.driver.MongoDBStoreDriver",
      "name": "scenario1_store",
      "config": {
        "connectionString": "mongodb://localhost:27017",
        "database": "scenario1_store",
        "collection": "data"
      },
      "jsonpathExpression": "jsonpath:1"
    }
  ]
}
----

* pipeId : As a data source provider, this is id identifies this data pipe uniquely with the Braineous Data Pipline Engine.
* configuration.storeDriver: MongoDB target store driver
* name: a user-friendly way to indentify the target store
* config.connectionString: MongoDB database connection string
* config.database: MongoDB database
* config.collection: MongoDB database collection

A data pipe can be configured with multiple target stores/systems associated with the same data pipe
for data delivery.

In the next Candidate Release, Braineous team will add support for more target stores and systems such as :

* Postgresql
* Mysql
* OracleDB
* Snowflake
* Microservices

Java Code - Register Pipe
[source,bash,subs=attributes+]
----
//get the configution file as String
String configLocation = "tutorial/usecase/scenario1/scenario1_pipe_config.json";

//parse into a JsonObject
json = Util.loadResource(configLocation);

//Use the registerPipe method on the DataPipeline SDK object to register the pipe
DataPipeline.registerPipe(json);
----

Java Code - Send Data for ingestion
[source,bash,subs=attributes+]
----
JsonObject configJson = JsonUtil.validateJson(json).getAsJsonObject();

//send source data through the pipeline
String pipeId = configJson.get("pipeId").getAsString();
String entity = TestConstants.ENTITY;
DataPipeline.sendData(pipeId, entity, datasetElement.toString());
----


== Verify all target collections receive the data

